# Generated by Django 6.0.2 on 2026-03-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_blog', 'Может управлять публикациями в блоге'), ('can_publish_blogpost', 'Может публиковать статьи')], 'verbose_name': 'Блоговая запись', 'verbose_name_plural': 'Блоговые записи'},
        ),
    ]
